# Dockerfile.test per MercurionTox21

FROM python:3.10.11-slim AS test

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY . .

RUN python -m venv .venv && \
    . .venv/bin/activate && \
    python -m pip install --upgrade pip && \
    pip install -r requirements.txt

CMD [".venv/bin/python", "-m", "inference"]
